apiVersion: v1
kind: Namespace
metadata:
  name: node-test
  labels:
    app.kubernetes.io/name: node-test
    app.kubernetes.io/instance: node-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: node-test
    labels:
        app: node-test
    name: node-test
spec:
  selector:
    matchLabels:
      app: node-test
  replicas: 1
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
        - name: node-test
          image: "andreimatei/node-test:1.0"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: node-test
  labels:
    app: node-test
  name: node-test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: node-test
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-test
  namespace: node-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: node-test.fineas.vienna.devopslog.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: node-test
          servicePort: 80